<?php
/**
 * Zigbee2Mqtt service configuration
 */
class ServiceConfig {

    /**
     * Path to the zigbee device
     * @var string */
    public $port = '';

    /**
     * Adapter type
     * @var string
     */
    public $adapter = '';
    /**
     * Serial baudrate. Empty string means: leave the value in
     * configuration.yaml untouched.
     * @var string
     */
    public $baudrate = '';

    /**
     * Serial hardware flow control. Empty string means: leave the value in
     * configuration.yaml untouched; "true" / "false" set it explicitly.
     * @var string
     */
    public $rtscts = '';

    /**
     * Enable zigbee2mqtt ui
     * @var bool
     */
    public $enableUI = false;

    /**
     * Port of the zigbee2mqtt ui
     * @var string
     */
    public $frontendPort = '8881';

    /**
     * Protect the zigbee2mqtt ui with a token (frontend.auth_token)
     * @var bool
     */
    public $frontendAuth = true;

    /**
     * Token of the zigbee2mqtt ui, generated by update-config.php
     * @var string
     */
    public $frontendToken = '';

    /**
     * Zigbee channel (11-26). Empty string means: leave the value in
     * configuration.yaml untouched.
     * @var string
     */
    public $channel = '';

    /**
     * Publish the availability (online/offline) of every device
     * @var bool
     */
    public $availability = true;

    /**
     * LoxBerry notification when a device goes offline
     * @var bool
     */
    public $notifyOffline = true;

    /**
     * LoxBerry notification when a battery runs low
     * @var bool
     */
    public $notifyBattery = true;

    /**
     * Battery level (percent) for the notification
     * @var string
     */
    public $batteryThreshold = '15';

    /**
     * Adapter types zigbee2mqtt accepts (serial.adapter)
     */
    const ADAPTERS = array("zstack", "ember", "deconz", "zigate", "zboss", "zoh", "ezsp");

    /**
     * Creates a new instance
     */
    public function __construct() {
    }


    /**
     * Loads the config. Only known settings are taken over - a setting of an
     * older version (e.g. permitJoin) is dropped on the next save.
     */
    public static function load() {
        $configfile = LBPCONFIGDIR . "/service.json";
        $data = json_decode(@file_get_contents($configfile), true);
        $class = new ServiceConfig();
        foreach ((is_array($data) ? $data : array()) as $key => $value) {
            if (property_exists($class, $key)) {
                $class->{$key} = $value;
            }
        }
        return $class;
    }

    /**
     * Checks the values. Returns a list of language keys of the errors.
     */
    public function validate() {
        $errors = array();
        if (!preg_match('/^[1-9][0-9]{0,4}$/', (string) $this->frontendPort) || (int) $this->frontendPort > 65535) {
            $errors[] = "ServiceConfig.ValFrontendPort";
        }
        if ((string) $this->adapter !== "" && !in_array($this->adapter, self::ADAPTERS, true)) {
            $errors[] = "ServiceConfig.ValAdapter";
        }
        if ((string) $this->baudrate !== "" && !preg_match('/^[0-9]{3,7}$/', (string) $this->baudrate)) {
            $errors[] = "ServiceConfig.ValBaudrate";
        }
        if ((string) $this->channel !== "" && ((int) $this->channel < 11 || (int) $this->channel > 26)) {
            $errors[] = "ServiceConfig.ValChannel";
        }
        if (!preg_match('/^[0-9]{1,2}$/', (string) $this->batteryThreshold) || (int) $this->batteryThreshold < 1) {
            $errors[] = "ServiceConfig.ValBattery";
        }
        if ((string) $this->port !== "" && !preg_match('#^(/dev/[A-Za-z0-9/_.:\-]+|tcp://[A-Za-z0-9.\-]+:[0-9]{1,5}|mdns://[A-Za-z0-9.\-]+)$#', (string) $this->port)) {
            $errors[] = "ServiceConfig.ValPort";
        }
        return $errors;
    }

    /**
     * Values that are not part of the form are kept from the saved config
     */
    public function keepFrom(ServiceConfig $saved) {
        $this->frontendToken = $saved->frontendToken;
    }

    /**
     * Saves the config
     */
    public function save() {
        $configfile = LBPCONFIGDIR . "/service.json";
        file_put_contents($configfile, $this->toJson());
    }

    /**
     * Creates a json string out of the config
     */
    public function toJson() {
        return json_encode($this, JSON_PRETTY_PRINT);
    }
}
